// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Training_App.DataAccess;

#nullable disable

namespace Training_App.DataAccess.Migrations
{
    [DbContext(typeof(TrainingAppDbContext))]
    partial class TrainingAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExerciseEntityTrainingEntity", b =>
                {
                    b.Property<Guid>("ExerciseEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrainingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ExerciseEntityId", "TrainingId");

                    b.HasIndex("TrainingId");

                    b.ToTable("ExerciseEntityTrainingEntity");
                });

            modelBuilder.Entity("Training_App.DataAccess.Entity.ApplicationUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("Training_App.DataAccess.Entity.ExerciseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CountOfBasicSets")
                        .HasColumnType("int");

                    b.Property<int>("CountOfWurmUpSets")
                        .HasColumnType("int");

                    b.Property<string>("Muscles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("Training_App.DataAccess.Entity.TrainingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Typename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserEntityId");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("ExerciseEntityTrainingEntity", b =>
                {
                    b.HasOne("Training_App.DataAccess.Entity.ExerciseEntity", null)
                        .WithMany()
                        .HasForeignKey("ExerciseEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Training_App.DataAccess.Entity.TrainingEntity", null)
                        .WithMany()
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Training_App.DataAccess.Entity.TrainingEntity", b =>
                {
                    b.HasOne("Training_App.DataAccess.Entity.ApplicationUserEntity", "ApplicationUserEntity")
                        .WithMany("TrainingEntity")
                        .HasForeignKey("ApplicationUserEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUserEntity");
                });

            modelBuilder.Entity("Training_App.DataAccess.Entity.ApplicationUserEntity", b =>
                {
                    b.Navigation("TrainingEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
